### ISSUE TITLE
Add the "show keyboard" function

### ISSUE THREAD

**Issue by Jaymz665** [PapierFliegr/OSK-Toggle#1]
Good day, your application is very well and harmoniously made. I would like to ask if it is possible to implement an additional function, "show keyboard" when pressed? There are many applications written in qt and OSK does not respond to them. Also, the gnome-mobile version is becoming relevant now, in which this function would be no less useful. Thank you in advance

**Comment by Jaymz665** [comment]
The question is interesting, on the one hand, you can add a new switch function so that it can be activated in the "gear" so that it switches the mode to a pop-up or permanent keyboard. On the other hand, it would be possible to make just a "fixed" keyboard. In this case, the functionality would be changed, but it could bear fruit.

**Comment by PapierFliegr** [comment]
I will probably drop this project since [GJS OSK](https://github.com/Vishram1123/gjs-osk) seems like the better solution.
Has the click function.
